name: Add short URL
description: Add a short URL to click.dino.icu
title: "Add short URL"
body:
  - type: input
    id: source
    attributes:
      label: Source
      description: Where should the short URL be at?
      placeholder: ex. hackclub
    validations:
      required: true
  - type: input
    id: destination
    attributes:
      label: Destination
      description: Where should the short URL redirect to?
      placeholder: ex. https://hackclub.com
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: Additional Information
      description: What's this short URL for?
      placeholder: ex. a form for the club fair
    validations:
      required: true
  - type: checkboxes
    id: conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow Hack Club's [Code of Conduct](https://hackclub.com/conduct)
      options:
        - label: I agree to follow Hack Club's Code of Conduct
          required: true
