name: Analyze Issue and Create Pull Request

permissions:
  contents: write

on:
  issues:
    types:
      - opened

jobs:
  analyzeAndCreatePR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Parse and Add Links
        run: |
          echo "$ISSUE_BODY" | awk '/### Source/{flag=1; next} /### Destination/{flag=0} flag' >> LINKS.txt
          echo " " >> LINKS.txt
          echo "$ISSUE_BODY" | awk '/### Destination/{flag=1; next} /### Additional Information/{flag=0} flag' >> LINKS.txt

      - name: Create Pull Request
        id: createPR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ${{ github.event.issue.number }}
          branch: add-link
          base: main
          title: ${{ github.event.issue.number }} automated PR
          body: |
            Closes #${{ github.event.issue.number }}
        env:
          ISSUE_BODY: ${{ steps.parseIssue.outputs.stdout }}
